AllCops:
  NewCops: enable
  TargetRubyVersion: 4.0

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Metrics/MethodLength:
  Max: 15

Naming/AccessorMethodName:
  Enabled: false

Naming/FileName:
  Exclude:
    - 'lib/hwf-dwp-api.rb'
    - 'lib/hwf-dwp-api/**/*'

Naming/PredicateMethod:
  Enabled: false

Style/ReturnNilInPredicateMethodDefinition:
  Enabled: false
